export type IconType =
  | "Academic Cap"
  | "Adjustments"
  | "Annotation"
  | "Archive"
  | "Arrow Circle Down"
  | "Arrow Circle Left"
  | "Arrow Circle Right"
  | "Arrow Circle Up"
  | "Arrow Down"
  | "Arrow Left"
  | "Arrow Narrow Down"
  | "Arrow Narrow Left"
  | "Arrow Narrow Right"
  | "Arrow Narrow Up"
  | "Arrow Right"
  | "Arrow Small Down"
  | "Arrow Small Left"
  | "Arrow Small Right"
  | "Arrow Small Up"
  | "Arrow Up"
  | "Arrows Expand"
  | "At Symbol"
  | "Backspace"
  | "Badge Check"
  | "Ban"
  | "Beaker"
  | "Bell"
  | "Book Open"
  | "Bookmark Alt"
  | "Bookmark"
  | "Briefcase"
  | "Cake"
  | "Calculator"
  | "Calendar"
  | "Camera"
  | "Cash"
  | "Chart Bar"
  | "Chart Pie"
  | "Chart Square Bar"
  | "Chat Alt 2"
  | "Chat Alt"
  | "Chat"
  | "Check Circle"
  | "Check"
  | "Chevron Double Down"
  | "Chevron Double Left"
  | "Chevron Double Right"
  | "Chevron Double Up"
  | "Chevron Down"
  | "Chevron Left"
  | "Chevron Right"
  | "Chevron Up"
  | "Chip"
  | "Clipboard Check"
  | "Clipboard Copy"
  | "Clipboard List"
  | "Clipboard"
  | "Clock"
  | "Cloud Download"
  | "Cloud Upload"
  | "Cloud"
  | "Code"
  | "Cog"
  | "Collection"
  | "Color Swatch"
  | "Credit Card"
  | "Cube Transparent"
  | "Cube"
  | "Currency Bangladeshi"
  | "Currency Dollar"
  | "Currency Euro"
  | "Currency Pound"
  | "Currency Rupee"
  | "Currency Yen"
  | "Cursor Click"
  | "Database"
  | "Desktop Computer"
  | "Device Mobile"
  | "Device Tablet"
  | "Document Add"
  | "Document Download"
  | "Document Duplicate"
  | "Document Remove"
  | "Document Report"
  | "Document Search"
  | "Document Text"
  | "Document"
  | "Dots Circle Horizontal"
  | "Dots Horizontal"
  | "Dots Vertical"
  | "Download"
  | "Duplicate"
  | "Emoji Happy"
  | "Emoji Sad"
  | "Exclamation Circle"
  | "Exclamation"
  | "External Link"
  | "Eye Off"
  | "Eye"
  | "Fast Forward"
  | "Film"
  | "Filter"
  | "Finger Print"
  | "Fire"
  | "Flag"
  | "Folder Add"
  | "Folder Download"
  | "Folder Open"
  | "Folder Remove"
  | "Folder"
  | "Gift"
  | "Globe Alt"
  | "Globe"
  | "Hand"
  | "Hashtag"
  | "Heart"
  | "Home"
  | "Identification"
  | "Inbox In"
  | "Inbox"
  | "Information Circle"
  | "Key"
  | "Library"
  | "Light Bulb"
  | "Lightning Bolt"
  | "Link"
  | "Location Marker"
  | "Lock Closed"
  | "Lock Open"
  | "Login"
  | "Logout"
  | "Mail Open"
  | "Mail"
  | "Map"
  | "Menu Alt 1"
  | "Menu Alt 2"
  | "Menu Alt 3"
  | "Menu Alt 4"
  | "Menu"
  | "Microphone"
  | "Minus Circle"
  | "Minus Sm"
  | "Minus"
  | "Moon"
  | "Music Note"
  | "Newspaper"
  | "Office Building"
  | "Paper Airplane"
  | "Paper Clip"
  | "Pause"
  | "Pencil Alt"
  | "Pencil"
  | "Phone Incoming"
  | "Phone Missed Call"
  | "Phone Outgoing"
  | "Phone"
  | "Photograph"
  | "Play"
  | "Plus Circle"
  | "Plus Sm"
  | "Plus"
  | "Presentation Chart Bar"
  | "Presentation Chart Line"
  | "Printer"
  | "Puzzle"
  | "Qrcode"
  | "Question Mark Circle"
  | "Receipt Refund"
  | "Receipt Tax"
  | "Refresh"
  | "Reply"
  | "Rewind"
  | "Rss"
  | "Save As"
  | "Save"
  | "Scale"
  | "Scissors"
  | "Search Circle"
  | "Search"
  | "Selector"
  | "Server"
  | "Share"
  | "Shield Check"
  | "Shield Exclamation"
  | "Shopping Bag"
  | "Shopping Cart"
  | "Sort Ascending"
  | "Sort Descending"
  | "Sparkles"
  | "Speakerphone"
  | "Star"
  | "Status Offline"
  | "Status Online"
  | "Stop"
  | "Sun"
  | "Support"
  | "Switch Horizontal"
  | "Switch Vertical"
  | "Table"
  | "Tag"
  | "Template"
  | "Terminal"
  | "Thumb Down"
  | "Thumb Up"
  | "Ticket"
  | "Translate"
  | "Trash"
  | "Trending Down"
  | "Trending Up"
  | "Truck"
  | "Upload"
  | "User Add"
  | "User Circle"
  | "User Group"
  | "User Remove"
  | "User"
  | "Users"
  | "Variable"
  | "Video Camera"
  | "View Boards"
  | "View Grid Add"
  | "View Grid"
  | "View List"
  | "Volume Off"
  | "Volume Up"
  | "Wifi"
  | "X Circle"
  | "X"
  | "Zoom In"
  | "Zoom Out";
